export * from './getTipoTrabajo'
export * from './getPersonalContrata'
export * from './updateTicket'
export * from "./getNodos"
export * from "./getRegistroTicket"
export * from "./getCargos"
export * from "./details"
export * from "./getRegistroTickets"
export * from "./getSingleRegistroTicket"
export * from "./downloadArchivoRespaldo"
export * from "./createTicket"
export * from "./getContratas"
export * from "./downloadZip"