export * from "./getFotoActividadPersonal"
export * from "./downloadArchivo"
export * from "./updateArchivoRespaldo"
export * from "./getTicketDetalles"
export * from "./downloadPdfDetalles"
export * from "./downloadFotoActividadPersonal"